package br.com.sistema.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import br.com.sistema.view.FormularioClientes;
import br.com.sistema.view.FormularioDetalheVenda;
import br.com.sistema.view.FormularioEstoque;
import br.com.sistema.view.FormularioFornecedores;
import br.com.sistema.view.FormularioFuncionarios;
import br.com.sistema.view.FormularioHistorico;
import br.com.sistema.view.FormularioLogin;
import br.com.sistema.view.FormularioPagamentos;
import br.com.sistema.view.FormularioProdutos;
import br.com.sistema.view.FormularioTotalDoDia;
import br.com.sistema.view.FormularioVendas;

/**
 *
 * @author rustz
 */
public class AreaTrabalho extends javax.swing.JFrame {

    public String usuarioLogado;
    
    
    public AreaTrabalho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgFundo/background.png"));
        Image image = icon.getImage();
        Painel_Desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(image, 0, 0,getWidth(),getHeight(),this);
            }

        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        abaFuncionarios = new javax.swing.JMenu();
        AFuncionarios = new javax.swing.JMenuItem();
        abaProdutos = new javax.swing.JMenu();
        AbaControleDeEstoque = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        abaFornecedores = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        abaclientes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        abaVendas = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        abaConfigurações = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        abaSair = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grsmartcell Sistema");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 165, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logado Por: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        lblLogado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLogado.setForeground(new java.awt.Color(255, 255, 255));
        lblLogado.setText("Joao da silva");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lblLogado))
        );

        Painel_Desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Painel_DesktopLayout = new javax.swing.GroupLayout(Painel_Desktop);
        Painel_Desktop.setLayout(Painel_DesktopLayout);
        Painel_DesktopLayout.setHorizontalGroup(
            Painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DesktopLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 987, Short.MAX_VALUE))
        );
        Painel_DesktopLayout.setVerticalGroup(
            Painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_DesktopLayout.createSequentialGroup()
                .addGap(0, 555, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        abaFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/group (1).png"))); // NOI18N
        abaFuncionarios.setText("Funcionarios");
        abaFuncionarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        AFuncionarios.setText("FormularioDeFuncionarios");
        AFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFuncionariosActionPerformed(evt);
            }
        });
        abaFuncionarios.add(AFuncionarios);

        jMenuBar1.add(abaFuncionarios);

        abaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/box.png"))); // NOI18N
        abaProdutos.setText("Produtos");
        abaProdutos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        AbaControleDeEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AbaControleDeEstoque.setText("ControleDeEstoque");
        AbaControleDeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaControleDeEstoqueActionPerformed(evt);
            }
        });
        abaProdutos.add(AbaControleDeEstoque);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("ConsultaDeProdutos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        abaProdutos.add(jMenuItem4);

        jMenuItem11.setText("FormularioDeProdutos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        abaProdutos.add(jMenuItem11);

        jMenuBar1.add(abaProdutos);

        abaFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/supplier.png"))); // NOI18N
        abaFornecedores.setText("Fornecedores");
        abaFornecedores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem10.setText("FormularioDeFornecedores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        abaFornecedores.add(jMenuItem10);

        jMenuBar1.add(abaFornecedores);

        abaclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/handshake.png"))); // NOI18N
        abaclientes.setText("Clientes");
        abaclientes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("FormularioDeClientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        abaclientes.add(jMenuItem2);

        jMenuBar1.add(abaclientes);

        abaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/profit-growth.png"))); // NOI18N
        abaVendas.setText("Vendas");
        abaVendas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Abrir PDV");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        abaVendas.add(jMenuItem5);

        jMenuItem6.setText("Posição do dia");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        abaVendas.add(jMenuItem6);

        jMenuItem7.setText("Historico de Vendas ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        abaVendas.add(jMenuItem7);

        jMenuBar1.add(abaVendas);

        abaConfigurações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/gear.png"))); // NOI18N
        abaConfigurações.setText("Configurações");
        abaConfigurações.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem8.setText("Trocar o usuario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        abaConfigurações.add(jMenuItem8);

        jMenuBar1.add(abaConfigurações);

        abaSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/switch.png"))); // NOI18N
        abaSair.setText("Sair");
        abaSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        abaSair.setIconTextGap(10);
        abaSair.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setText("Sair do Sistema");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        abaSair.add(jMenuItem9);

        jMenuBar1.add(abaSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        FormularioClientes fc = new FormularioClientes(this,true);
        fc.setModal(rootPaneCheckingEnabled);
        fc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        this.setExtendedState(AreaTrabalho.MAXIMIZED_BOTH);
        lblLogado.setText(usuarioLogado);
        
    }//GEN-LAST:event_formWindowActivated

    private void AFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFuncionariosActionPerformed

        FormularioFuncionarios fc = new FormularioFuncionarios(this,true);
        fc.setModal(rootPaneCheckingEnabled);
        fc.setVisible(true);
        
    }//GEN-LAST:event_AFuncionariosActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FormularioFornecedores fc = new FormularioFornecedores(this,true);
        fc.setModal(rootPaneCheckingEnabled);
        fc.setVisible(true);

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FormularioProdutos fc = new FormularioProdutos(this,true);
        fc.setModal(rootPaneCheckingEnabled);
        fc.Painel_guias_gerais.setSelectedIndex(1);

        fc.setVisible(true);    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FormularioProdutos consultaProdutos = new FormularioProdutos(this,true);
        consultaProdutos.Painel_guias_gerais.setSelectedIndex(0);
        consultaProdutos.setModal(rootPaneCheckingEnabled);
        consultaProdutos.setVisible(true);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void AbaControleDeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaControleDeEstoqueActionPerformed

        FormularioEstoque fc = new FormularioEstoque(this,true);
        fc.setModal(rootPaneCheckingEnabled);
        fc.setVisible(true);

    }//GEN-LAST:event_AbaControleDeEstoqueActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormularioVendas consultaProdutos = new FormularioVendas();
        consultaProdutos.setVisible(true);    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        FormularioTotalDoDia total_do_dia = new FormularioTotalDoDia(this,true);
        total_do_dia.setModal(rootPaneCheckingEnabled);
        total_do_dia.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FormularioHistorico historico = new FormularioHistorico();
        historico.setVisible(true);


    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        FormularioLogin login = new FormularioLogin();
        this.dispose();
        login.setVisible(true);
        

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        int janela = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair do sistema?");
        if(janela==0){
            System.exit(0);
        }else if(janela==2){
            JOptionPane.showMessageDialog(null,"Cancelando...");
        }


    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaTrabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem AFuncionarios;
    public javax.swing.JMenuItem AbaControleDeEstoque;
    private javax.swing.JDesktopPane Painel_Desktop;
    private javax.swing.JMenu abaConfigurações;
    private javax.swing.JMenu abaFornecedores;
    public javax.swing.JMenu abaFuncionarios;
    private javax.swing.JMenu abaProdutos;
    private javax.swing.JMenu abaSair;
    private javax.swing.JMenu abaVendas;
    private javax.swing.JMenu abaclientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogado;
    // End of variables declaration//GEN-END:variables
}
