package br.com.sistema.view;

import br.com.sistema.dao.ProdutosDAO;
import br.com.sistema.model.Produtos;
import br.com.sistema.utilitarios.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rustz
 */
public class FormularioEstoque extends javax.swing.JDialog {
    
 public void listar() {
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.lista();

        // Obtém o modelo da tabela e limpa as linhas existentes
        DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
        dados.setRowCount(0); // Limpa as linhas

        // Adiciona cada cliente como uma nova linha na tabela
        for (Produtos c : lista) {
            dados.addRow(new Object[] {
                c.getId(),          // id
                c.getNome(),        // nome
                c.getPreco(),      
                c.getEstoque()
            });
        }

    }
    
    
    public FormularioEstoque(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Painel_guias_gerais = new javax.swing.JTabbedPane();
        painel_dados_pessoais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidadeAtual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAdicionar = new javax.swing.JTextField();
        bntAdicionar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRemove = new javax.swing.JTextField();
        bntremover = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estoque");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("código: ");

        txtcodigo.setEditable(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Nome do Produto:");

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade atual:");

        txtQuantidadeAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeAtualActionPerformed(evt);
            }
        });
        txtQuantidadeAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeAtualKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Quatidade Adicionar:");

        txtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdicionarActionPerformed(evt);
            }
        });
        txtAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdicionarKeyTyped(evt);
            }
        });

        bntAdicionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bntAdicionar.setText("Adicionar");
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Quatidade Remover:");

        txtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemoveActionPerformed(evt);
            }
        });
        txtRemove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRemoveKeyTyped(evt);
            }
        });

        bntremover.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bntremover.setText("Remover");
        bntremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_dados_pessoaisLayout = new javax.swing.GroupLayout(painel_dados_pessoais);
        painel_dados_pessoais.setLayout(painel_dados_pessoaisLayout);
        painel_dados_pessoaisLayout.setHorizontalGroup(
            painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                        .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 214, Short.MAX_VALUE))
                    .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                                .addComponent(txtRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntremover)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntAdicionar)))))
                .addContainerGap())
        );
        painel_dados_pessoaisLayout.setVerticalGroup(
            painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(22, 22, 22)
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAdicionar))
                .addGap(18, 18, 18)
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntremover))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Painel_guias_gerais.addTab("Dados do Produto", painel_dados_pessoais);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.sistema.imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome do Produto", "Preço do Produto", "Quantidade de Produtos"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Painel_guias_gerais)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnNovo)
                .addGap(45, 45, 45)
                .addComponent(BtnSalvar)
                .addGap(68, 68, 68)
                .addComponent(BtnEditar)
                .addGap(27, 27, 27)
                .addComponent(BtnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_guias_gerais, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(BtnEditar)
                    .addComponent(BtnExcluir))
                .addContainerGap())
        );

        Painel_guias_gerais.getAccessibleContext().setAccessibleName("Consulta de Produtos");
        Painel_guias_gerais.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
            Utilitarios util = new Utilitarios();
            util.LimpaTela(painel_dados_pessoais);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
     Produtos obj = new Produtos();
     obj.setNome(txtnome.getText());
     obj.setPreco(txtQuantidadeAtual.getText());
     obj.setEstoque(txtAdicionar.getText());
     ProdutosDAO dao = new ProdutosDAO();
     dao.salvar(obj);
     Utilitarios novo = new Utilitarios();
     novo.LimpaTela(painel_dados_pessoais);
     
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        listar();


    }//GEN-LAST:event_formWindowActivated

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
    Produtos obj = new Produtos();

    // Configurar os valores a partir dos campos de texto
    obj.setId(Integer.parseInt(txtcodigo.getText())); // Adiciona o ID do cliente
    obj.setNome(txtnome.getText());
    obj.setPreco(txtQuantidadeAtual.getText());
    obj.setEstoque(txtAdicionar.getText());

    // Chamar o DAO para editar o cliente
    ProdutosDAO dao = new ProdutosDAO();
    dao.Editar(obj);

    // Limpar os campos após a edição
    Utilitarios novo = new Utilitarios();
    novo.LimpaTela(painel_dados_pessoais);

        

    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
     Produtos obj = new Produtos();
     obj.setId(Integer.valueOf(txtcodigo.getText()));
     ProdutosDAO dao = new ProdutosDAO();
     dao.Excluir(obj);
     Utilitarios util = new Utilitarios();
     util.LimpaTela(painel_dados_pessoais);

    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String nome = txtnome.getText();
        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        obj = dao.BuscarProduto(nome);
        if (obj.getNome() != null){

            txtcodigo.setText(String.valueOf(obj.getId()));
            txtnome.setText(obj.getNome());
            txtQuantidadeAtual.setText(obj.getEstoque());
        }else{

            JOptionPane.showMessageDialog(null, "Produto não encontrado");

        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            String nome = txtnome.getText();
            Produtos obj = new Produtos();
            ProdutosDAO dao = new ProdutosDAO();

            obj = dao.BuscarProduto(nome);
            if (obj.getNome() != null){

                txtcodigo.setText(String.valueOf(obj.getId()));
                txtnome.setText(obj.getNome());
                txtQuantidadeAtual.setText(obj.getEstoque());


            }else{

                JOptionPane.showMessageDialog(null, "Produto não encontrado");

            }

        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtQuantidadeAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeAtualActionPerformed
    try {
            String precoTexto = txtQuantidadeAtual.getText();

            // Impedir valores vazios
            if (precoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo de preço não pode estar vazio.");
                return;
            }

            // Verificar se o valor é válido como número decimal
            double preco = Double.parseDouble(precoTexto);

            // Impedir valores negativos ou zero
            if (preco <= 0) {
                JOptionPane.showMessageDialog(null, "O preço deve ser maior que zero.");
                txtQuantidadeAtual.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Preço válido: " + preco);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um valor numérico válido.");
            txtQuantidadeAtual.requestFocus();
        }
    }//GEN-LAST:event_txtQuantidadeAtualActionPerformed

    private void txtQuantidadeAtualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeAtualKeyTyped
char c = evt.getKeyChar();

// Permitir apenas números e ponto decimal
if (!Character.isDigit(c) && c != ',') {
    evt.consume(); // Impede caracteres inválidos
}

// Impedir múltiplos pontos decimais
if (c == '.' && txtQuantidadeAtual.getText().contains(".")) {
    evt.consume(); // Apenas um ponto é permitido
}
    }//GEN-LAST:event_txtQuantidadeAtualKeyTyped

    private void txtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdicionarActionPerformed
    try {
            String EstoqueTexto = txtAdicionar.getText();

            // Impedir valores vazios
            if (EstoqueTexto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo de estoque não pode estar vazio.");
                return;
            }

            // Verificar se o valor é válido como número decimal
            double estoque = Double.parseDouble(EstoqueTexto);

            // Impedir valores negativos ou zero
            if (estoque <= 0) {
                JOptionPane.showMessageDialog(null, "O Estoque deve ser maior que zero.");
                txtQuantidadeAtual.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Estoque válido: " + estoque);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um valor numérico válido.");
            txtAdicionar.requestFocus();
        }    }//GEN-LAST:event_txtAdicionarActionPerformed

    private void txtAdicionarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdicionarKeyTyped
char c = evt.getKeyChar();

// Permitir apenas números e ponto decimal
if (!Character.isDigit(c) && c != ',') {
    evt.consume(); // Impede caracteres inválidos
}

// Impedir múltiplos pontos decimais
if (c == '.' && txtAdicionar.getText().contains(".")) {
    evt.consume(); // Apenas um ponto é permitido
}
    }//GEN-LAST:event_txtAdicionarKeyTyped

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
try {
    // Obtem os valores dos campos
    int idProduto = Integer.parseInt(txtcodigo.getText());
    int qtdAtual = Integer.parseInt(txtQuantidadeAtual.getText());
    int qtdNova = Integer.parseInt(txtAdicionar.getText());

    // Calcula a nova quantidade
    int qtdAtualizada = qtdAtual + qtdNova;

    // Atualiza o estoque no banco de dados
    ProdutosDAO daop = new ProdutosDAO();
    daop.AdicionarEstoque(idProduto, qtdAtualizada);

    // Exibe mensagem de sucesso
    JOptionPane.showMessageDialog(null, "Adicionado com sucesso ao estoque!");
    new Utilitarios().LimpaTela(painel_dados_pessoais);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Erro: Insira apenas números nos campos. " + e.getMessage());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
}


    }//GEN-LAST:event_bntAdicionarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

        Painel_guias_gerais.setSelectedIndex(0);
        txtcodigo.setText(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
        txtnome.setText(tabela.getValueAt(tabela.getSelectedRow(),1).toString());
        txtQuantidadeAtual.setText(tabela.getValueAt(tabela.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void txtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemoveActionPerformed

    private void txtRemoveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoveKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemoveKeyTyped

    private void bntremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntremoverActionPerformed
try {
    // Obtem os valores dos campos
    int idProduto = Integer.parseInt(txtcodigo.getText());
    int qtdAtual = Integer.parseInt(txtQuantidadeAtual.getText());
    int qtdNova = Integer.parseInt(txtRemove.getText());

    // Calcula a nova quantidade
    int qtdAtualizada = qtdAtual - qtdNova;

    // Atualiza o estoque no banco de dados
    ProdutosDAO daop = new ProdutosDAO();
    daop.AdicionarEstoque(idProduto, qtdAtualizada);

    JOptionPane.showMessageDialog(null, "Removido com sucesso ao estoque!");
    new Utilitarios().LimpaTela(painel_dados_pessoais);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Erro: Insira apenas números nos campos. " + e.getMessage());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
}    }//GEN-LAST:event_bntremoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FormularioEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTabbedPane Painel_guias_gerais;
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntremover;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel painel_dados_pessoais;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtAdicionar;
    private javax.swing.JTextField txtQuantidadeAtual;
    private javax.swing.JTextField txtRemove;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
